enum HandshakeType {
	HELLO_REQUEST_RESERVED = 0,
	CLIENT_HELLO = 1,
	SERVER_HELLO = 2,
	HELLO_VERIFY_REQUEST_RESERVED = 3,
	NEW_SESSION_TICKET = 4,
	END_OF_EARLY_DATA = 5,
	HELLO_RETRY_REQUEST_RESERVED = 6,
	ENCRYPTED_EXTENSIONS = 8,
	CERTIFICATE = 11,
	SERVER_KEY_EXCHANGE_RESERVED = 12,
	CERTIFICATE_REQUEST = 13,
	SERVER_HELLO_DONE_RESERVED = 14,
	CERTIFICATE_VERIFY = 15,
	CLIENT_KEY_EXCHANGE_RESERVED = 16,
	FINISHED = 20,
	CERTIFICATE_URL_RESERVED = 21,
	CERTIFICATE_STATUS_RESERVED = 22,
	SUPPLEMENTAL_DATA_RESERVED = 23,
	KEY_UPDATE = 24,
	MESSAGE_HASH = 254,
}

export default HandshakeType;
